/*=========================================================================

  University of Pittsburgh Bioengineering 1351/2351
  Final project example code

  Copyright (c) 2011 by Damion Shelton

  All rights reserved.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/

#ifndef _FinalProjectWindow_h
#define _FinalProjectWindow_h

#include <QImage>

// qmainwindow is part of Qt
#include "qmainwindow.h"

// ui_FinalProjectWindow is automatically generated by Qt from the UI file
#include "ui_FinalProject.h"

// These two are files I wrote
#include "FinalProjectApp.h"

// This is an example of multiple inheritance. The FinalProjectWindow class derives
// from BOTH QMainWindow and the Ui_MainWindow class defined in the UI file
class FinalProjectWindow : public QMainWindow, public Ui_MainWindow
{
Q_OBJECT

public:

  /** Constructor */
  FinalProjectWindow(QWidget* parent = 0);

  /** Destructor */
  ~FinalProjectWindow();

public slots:

  /** Receive an image to display */
  void OnReceiveImage(QImage image);

protected:

  /** Handle closing the main window */
  void closeEvent(QCloseEvent *event);

  /** Timer event handler - lowercase name is overload */
  void timerEvent(QTimerEvent* event);

  /** Realtime update function called in response to timer events */
  void RealtimeUpdate();

  /** Event timer */
  int m_TimerID;

    /** Viewfinder graphics scene */
  QGraphicsScene* m_GraphicsScene;

  /** Viewfinder image for display */
  QGraphicsPixmapItem* m_PixmapItem;

  /** App */
  FinalProjectApp* m_App;
};

#endif
